--===========================================================================
DROP TABLE IF EXISTS amc_core.ic_procedure_note_thorax_drain CASCADE;

CREATE TABLE amc_core.ic_procedure_note_thorax_drain (
  order_id text PRIMARY KEY,

  pseudo_id text,
  patient_contact_id text,
  hospital_location text,
  intervention_date_time timestamptz,
  intervention_name text,

  start_procedure timestamptz,
  informed_consent text,
  correct_patient text,
  correct_procedure text,
  correct_side text,
  relevant_comorbidity_medication_coagulation_status_allergies text,
  complications_discussed text,
  severe_coagulation_disorders text,
  sedation_and_analgesia text,
  thorax_suction_drainage_set text,
  sterile_gloves_coat_cloths_chlorhexide_at_alcohol70percent text,
  non_soluble_suture text,
  wound_care_kit text,
  kelly_clip text,
  thoracic_drain_of_pneumocath text,
  lolale_anesthetics_puller_syringe_green_needle text,
  pneumothorax_insertion_kit text,
  tiewraps_and_tightening_gun text,
  minimum_two_venous_accessions text,
  determine_position_thoraxdrain_and_position_patint text,
  pulse_oximetry text,
  time_out_executed text,

  indications text,
  indication_hemoneumothorax text,
  indication_clap_lung text,
  indication_pleural_effusion text,
  indication_chylothorax text,
  indication_hemothorax text,
  indication_emypeem text,
  indication_stress_pneumothorax text,

  sedation text,
  start_sedation timestamptz,
  end_sedation timestamptz,
  anesthesia_method text,
  local_anaesthesia text,
  anesthetic_total_ml numeric,
  patient_sedated text,
  level_sedation text,
  level_sedation_all_anesthesia text,
  level_sedation_anxiolysis text,
  level_sedation_regular_sedation text,
  level_sedation_deep_sedation text,
  monitoring_vital_data_during_sedation text,
  analgesics text,

  preparation text,
  thoraxdrain_location text,
  orientation_drain text,
  size_scalpel_raw text,
  size_scalpel numeric,
  type_drain text,
  size_drain_french_raw text,
  size_drain_french numeric,
  catheter_size numeric,
  method_dissection text,
  echo_guided text,
  aspect_drainage text,
  quantity_drainage numeric,
  suture text,
  bandage text,

  radiographic_findings text,
  radiographic_findings_repositioned text,
  radio_findings_good_position text,
  complications text,
  end_procedure text,
  tolerance_patient_for_intervention text,
  intervention_remarks text,

  source text,
  dcm_refreshed_date_time timestamptz,
  issue_dt timestamptz
);

INSERT INTO amc_core.ic_procedure_note_thorax_drain (
  order_id,
  pseudo_id,
  patient_contact_id,
  hospital_location,
  intervention_date_time,
  intervention_name,
  start_procedure,
  informed_consent,
  correct_patient,
  correct_procedure,
  correct_side,
  relevant_comorbidity_medication_coagulation_status_allergies,
  complications_discussed,
  severe_coagulation_disorders,
  sedation_and_analgesia,
  thorax_suction_drainage_set,
  sterile_gloves_coat_cloths_chlorhexide_at_alcohol70percent,
  non_soluble_suture,
  wound_care_kit,
  kelly_clip,
  thoracic_drain_of_pneumocath,
  lolale_anesthetics_puller_syringe_green_needle,
  pneumothorax_insertion_kit,
  tiewraps_and_tightening_gun,
  minimum_two_venous_accessions,
  determine_position_thoraxdrain_and_position_patint,
  pulse_oximetry,
  time_out_executed,
  indications,
  indication_hemoneumothorax,
  indication_clap_lung,
  indication_pleural_effusion,
  indication_chylothorax,
  indication_hemothorax,
  indication_emypeem,
  indication_stress_pneumothorax,
  sedation,
  start_sedation,
  end_sedation,
  anesthesia_method,
  local_anaesthesia,
  anesthetic_total_ml,
  patient_sedated,
  level_sedation,
  level_sedation_all_anesthesia,
  level_sedation_anxiolysis,
  level_sedation_regular_sedation,
  level_sedation_deep_sedation,
  monitoring_vital_data_during_sedation,
  analgesics,
  preparation,
  thoraxdrain_location,
  orientation_drain,
  size_scalpel_raw, size_scalpel,
  type_drain,
  size_drain_french_raw, size_drain_french,
  catheter_size,
  method_dissection,
  echo_guided,
  aspect_drainage,
  quantity_drainage,
  suture,
  bandage,
  radiographic_findings,
  radiographic_findings_repositioned,
  radio_findings_good_position,
  complications,
  end_procedure,
  tolerance_patient_for_intervention,
  intervention_remarks,
  source,
  dcm_refreshed_date_time,
  issue_dt
)
SELECT
  NULLIF(order_id, ''),
  NULLIF(pseudo_id, ''),
  NULLIF(patient_contact_id, ''),
  NULLIF(hospital_location, ''),
  NULLIF(intervention_date_time, '')::timestamptz,
  NULLIF(intervention_name, ''),

  NULLIF(start_procedure, '')::timestamptz,
  NULLIF(informed_consent, ''),
  NULLIF(correct_patient, ''),
  NULLIF(correct_procedure, ''),
  NULLIF(correct_side, ''),
  NULLIF(relevant_comorbidity_medication_coagulation_status_allergies, ''),
  NULLIF(complications_discussed, ''),
  NULLIF(severe_coagulation_disorders, ''),
  NULLIF(sedation_and_analgesia, ''),
  NULLIF(thorax_suction_drainage_set, ''),
  NULLIF(sterile_gloves_coat_cloths_chlorhexide_at_alcohol70percent, ''),
  NULLIF(non_soluble_suture, ''),
  NULLIF(wound_care_kit, ''),
  NULLIF(kelly_clip, ''),
  NULLIF(thoracic_drain_of_pneumocath, ''),
  NULLIF(lolale_anesthetics_puller_syringe_green_needle, ''),
  NULLIF(pneumothorax_insertion_kit, ''),
  NULLIF(tiewraps_and_tightening_gun, ''),
  NULLIF(minimum_two_venous_accessions, ''),
  NULLIF(determine_position_thoraxdrain_and_position_patint, ''),
  NULLIF(pulse_oximetry, ''),
  NULLIF(time_out_executed, ''),

  NULLIF(indications, ''),
  NULLIF(indication_hemoneumothorax, ''),
  NULLIF(indication_clap_lung, ''),
  NULLIF(indication_pleural_effusion, ''),
  NULLIF(indication_chylothorax, ''),
  NULLIF(indication_hemothorax, ''),
  NULLIF(indication_emypeem, ''),
  NULLIF(indication_stress_pneumothorax, ''),

  NULLIF(sedation, ''),
  NULLIF(start_sedation, '')::timestamptz,
  NULLIF(end_sedation, '')::timestamptz,
  NULLIF(anesthesia_method, ''),
  NULLIF(local_anaesthesia, ''),
  CASE WHEN trim(anesthetic_total_ml) ~ '^[-+]?(?:[0-9]+\.?[0-9]*|\.[0-9]+)$'
    THEN trim(anesthetic_total_ml)::numeric END,
  NULLIF(patient_sedated, ''),
  NULLIF(level_sedation, ''),
  NULLIF(level_sedation_all_anesthesia, ''),
  NULLIF(level_sedation_anxiolysis, ''),
  NULLIF(level_sedation_regular_sedation, ''),
  NULLIF(level_sedation_deep_sedation, ''),
  NULLIF(monitoring_vital_data_during_sedation, ''),
  NULLIF(analgesics, ''),

  NULLIF(preparation, ''),
  NULLIF(thoraxdrain_location, ''),
  NULLIF(orientation_drain, ''),
  NULLIF(size_scalpel, ''),

  CASE WHEN trim(size_scalpel) ~ '^[-+]?(?:[0-9]+\.?[0-9]*|\.[0-9]+)$'
    THEN trim(size_scalpel)::numeric END,
  NULLIF(type_drain, ''),
  NULLIF(size_drain_french, ''),

  CASE WHEN trim(size_drain_french) ~ '^[-+]?(?:[0-9]+\.?[0-9]*|\.[0-9]+)$'
    THEN trim(size_drain_french)::numeric END,
  CASE WHEN trim(catheter_size) ~ '^[-+]?(?:[0-9]+\.?[0-9]*|\.[0-9]+)$'
    THEN trim(catheter_size)::numeric END,
  NULLIF(method_dissection, ''),
  NULLIF(echo_guided, ''),
  NULLIF(aspect_drainage, ''),
  CASE WHEN trim(quantity_drainage) ~ '^[-+]?(?:[0-9]+\.?[0-9]*|\.[0-9]+)$'
    THEN trim(quantity_drainage)::numeric END,
  NULLIF(suture, ''),
  NULLIF(bandage, ''),

  NULLIF(radiographic_findings, ''),
  NULLIF(radiographic_findings_repositioned, ''),
  NULLIF(radio_findings_good_position, ''),
  NULLIF(complications, ''),
  NULLIF(end_procedure, ''),
  NULLIF(tolerance_patient_for_intervention, ''),
  NULLIF(intervention_remarks, ''),

  NULLIF(source, ''),
  NULLIF(dcm_refreshed_date_time, '')::timestamptz,
  NULLIF(issue_dt, '')::timestamptz

FROM amc_raw.ic_procedure_note_thorax_drain

WHERE NULLIF(order_id, '') IS NOT NULL;

-- indexes
CREATE INDEX IF NOT EXISTS idx_core_thorax_drain_contact
  ON amc_core.ic_procedure_note_thorax_drain(patient_contact_id);

