--===========================================================================
-- New table, first appears in the 2026-09-08 extract. Types/casts mirror
-- echo_measurement_heart column-for-column (456 of 457 columns match that
-- table's existing definitions exactly by name); e_f_slope is the one new
-- column, typed numeric to match the near-identical mv_e_f_slope numeric
-- already on echo_measurement_heart.
DROP TABLE IF EXISTS amc_core.echo_measurement_heart_center_extra_check CASCADE;

CREATE TABLE amc_core.echo_measurement_heart_center_extra_check (
  id bigserial PRIMARY KEY,
  pseudo_id text,
  examination_date date,
  hospital_location text,
  bmi numeric,
  bsa numeric,
  ao_desc_max_pg numeric,
  diam_sinus_valsalva numeric,
  ao_root_diam numeric,
  ao_desc_abd_diam numeric,
  isthmus_ao_diam numeric,
  ao_desc_vmax numeric,
  ao_asc_vmax numeric,
  ao_bow_diam numeric,
  ao_asc_max_pg numeric,
  ao_asc_diam numeric,
  ao_root_diam_duplicate numeric,
  dist_diam_ao_bow numeric,
  ao_st_junct_diam numeric,
  ao_desc_thorac_diam numeric,
  av_slip numeric,
  ar_dec_slope numeric,
  av_ci numeric,
  av_diam numeric,
  av_hr numeric,
  av_max_pg numeric,
  av_co numeric,
  avet numeric,
  ava_planimetry numeric,
  av_vti numeric,
  ar_as_skin text,
  ar_vena_contracta numeric,
  ar_rad numeric,
  av_vmax numeric,
  ar_vti numeric,
  ar_flow numeric,
  ar_max_pg numeric,
  av_vmean numeric,
  av_slip_duplicate numeric,
  ar_vmax numeric,
  av_surface numeric,
  ava_vmax numeric,
  ar_vmean numeric,
  ar_rv numeric,
  ar_ero numeric,
  av_mean_pg numeric,
  av_sv numeric,
  ava_vti_index numeric,
  ar_dec_time numeric,
  avai_planimetry numeric,
  ar_rf numeric,
  ar_pht numeric,
  ava_vti numeric,
  ar_mean_pg numeric,
  ar_vmax_duplicate numeric,
  av_si numeric,
  av_diam_index numeric,
  av_diam_duplicate numeric,
  lpa_vmax numeric,
  lpa_max_pg numeric,
  rpa_vmax numeric,
  rpa text,
  rpa_max_pg numeric,
  mpa_vmax numeric,
  lpa text,
  laesv_a_l_a2c numeric,
  la_short numeric,
  laedv_mod_bip numeric,
  la_lang text,
  la_diam numeric,
  la_area numeric,
  laesv_mod_a4c numeric,
  lald_a4c numeric,
  laedv_a_l_a4c numeric,
  laesvi_mod_bip numeric,
  laesv_mod_bip numeric,
  la_over_ao numeric,
  laesvi_a_l numeric,
  la_diam_duplicate numeric,
  laesv_a_l_a4c numeric,
  laa_d2 numeric,
  laedvi_a_l numeric,
  laedv_mod_a2c numeric,
  lals_a4c numeric,
  laesv_a_l_bip numeric,
  laesv_mod_a2c numeric,
  laedv_mod_a4c numeric,
  laedv_a_l_bip numeric,
  laad_a4c numeric,
  laas_a4c numeric,
  laa_d1 numeric,
  laedv_a_l_a2c numeric,
  p_vein_s_vmax numeric,
  p_vein_a_duration numeric,
  p_vein_a_vmax numeric,
  p_vein_s_over_d numeric,
  p_vein_d_vmax numeric,
  l_ader_a_duration_about_mv_a_duration numeric,
  mr_vmax numeric,
  e_f_slope numeric,
  mv_a_velocity numeric,
  mr_vena_contracta numeric,
  mv_e_over_a numeric,
  mv_e_deriv numeric,
  mv_e_deriv_sept numeric,
  mv_e_deriv_lat numeric,
  mv_e_over_e_deriv_avg numeric,
  mv_a_duration numeric,
  mv_a_deriv_lat numeric,
  mr_vmax_duplicate numeric,
  mr_vmean numeric,
  mv_e_deriv_over_a_deriv_lat numeric,
  mv_e_over_e_deriv_lat numeric,
  mv_co numeric,
  mr_dp_over_dt numeric,
  mva_pht numeric,
  epss numeric,
  mv_pht numeric,
  mv_max_pg numeric,
  mr_rad numeric,
  mv_sv numeric,
  mv_ivrt numeric,
  mr_as_vel numeric,
  mv_acc_time numeric,
  mr_mean_pg numeric,
  mco numeric,
  mv_s_deriv_lat numeric,
  mv_vmax numeric,
  mv_ann_diam numeric,
  mr_max_pg numeric,
  mva_vti numeric,
  mr_ero numeric,
  mr_flow numeric,
  mv_mean_pg numeric,
  mv_s_deriv_sept numeric,
  mv_vmean numeric,
  mv_e_over_e_deriv numeric,
  mr_vti numeric,
  mv_ivct numeric,
  mv_e_deriv_avg numeric,
  mr_vti_duplicate numeric,
  mv_e_over_e_deriv_sept numeric,
  mv_hr numeric,
  mr_rv numeric,
  mr_rf numeric,
  mv_e_velocity numeric,
  mv_e_deriv_over_a_deriv_sept numeric,
  mva_planimetry numeric,
  mv_vti numeric,
  mv_dec_time numeric,
  mv_a_deriv_sept numeric,
  mv_dec_slope numeric,
  bd_syst numeric,
  bd_diast numeric,
  heart_rate numeric,
  lvpw_perc numeric,
  glps_afi_a2c numeric,
  lvids_index numeric,
  mal_pieksys_sl_a4c numeric,
  ivss numeric,
  lvidd_index numeric,
  aa_pieksys_sl_a2c numeric,
  al_pieksys_sl_a4c numeric,
  lvdd_major_a4c numeric,
  lvad_a4c numeric,
  mas_pieksys_sl_aplax numeric,
  mis_pieksys_sl_a4c numeric,
  lvpwd numeric,
  lvad_paras_pm numeric,
  ivsd numeric,
  lvad numeric,
  lvids_index_duplicate numeric,
  glps_afi_a4c numeric,
  limp text,
  lvas_a4c numeric,
  glps_4d_auto_lvq text,
  ma_pieksys_sl_a2c numeric,
  lvids numeric,
  ba_pieksys_sl_a2c numeric,
  bi_pieksys_sl_a2c numeric,
  mi_pieksys_sl_a2c numeric,
  ap_pieksys_sl_aplax numeric,
  lvas numeric,
  lvas_paras_pm numeric,
  lvas_epi_paras_pm numeric,
  aas_pieksys_sl_aplax numeric,
  lvidd_index_duplicate numeric,
  vsd_size_2 numeric,
  bil_pieksys_sl_aplax numeric,
  lv_hr numeric,
  lvidd numeric,
  lvidd_duplicate numeric,
  lvds_major_a4c numeric,
  lvids_duplicate numeric,
  mil_pieksys_sl_aplax numeric,
  lv_hr_duplicate numeric,
  lvld_apical numeric,
  ivss_duplicate numeric,
  lvpws numeric,
  lvrwt numeric,
  lvpwd_duplicate numeric,
  lvdd_major_a2c numeric,
  bas_pieksys_sl_aplax numeric,
  glps_afi_lax numeric,
  bis_pieksys_sl_a4c numeric,
  iv_sd_duplicate numeric,
  lv_hr_bpm_2 numeric,
  vsd_size_1 numeric,
  lvad_epi_paras_pm numeric,
  lvds_major_a2c numeric,
  as_pieksys_sl_a4c numeric,
  glps_avg_afi text,
  lvpw_perc_duplicate numeric,
  lv_fs numeric,
  ball_pieksys_sl_a4c numeric,
  ivs_perc_2d numeric,
  ai_pieksys_sl_a2c numeric,
  lv_fs_duplicate numeric,
  lvpws_duplicate numeric,
  lvls_apical numeric,
  lvot_co numeric,
  lvot_diam numeric,
  dimensionless_index numeric,
  lvot_vmean numeric,
  lvot_sv numeric,
  lvot_vmax numeric,
  lvot_mean_pg numeric,
  lvot_ci numeric,
  lvot_vti numeric,
  lvot_svi numeric,
  lvot_surface numeric,
  lvot_max_pg numeric,
  lvef_auto_ef_a2c numeric,
  lvesv_4d_auto_lvq numeric,
  lvesv_auto_ef_a4c numeric,
  lvef_mod_bip numeric,
  lvedv_4d_auto_lvq numeric,
  lvesv_mod numeric,
  lvedv_teich numeric,
  lvesv_cube numeric,
  lvedv_auto_ef_a2c numeric,
  lvef_mod numeric,
  lvedv_auto_ef_a4c numeric,
  lvedvi_mod_a2c numeric,
  lvef_a_l numeric,
  lvesv_mod_a2c numeric,
  lvef_mod_a2c numeric,
  lvesv_a_l numeric,
  lvedv_teich_duplicate numeric,
  lvesv_geom numeric,
  lvesv_mod_bip numeric,
  lvedvi_mod_bip numeric,
  lvesv_teich numeric,
  lvedvi_teich numeric,
  lvef_4d_auto_lvq numeric,
  lvedv_a_l numeric,
  lvesvi_mod_a2c numeric,
  lvesv_teich_duplicate numeric,
  lvedv_cube numeric,
  lvedvi_teich_duplicate numeric,
  lvef_auto_ef_bip numeric,
  lvedv_mod_bip numeric,
  lvesvi_mod_bip numeric,
  lvesvi_mod_a4c numeric,
  lvef_cube numeric,
  lvesv_cube_duplicate numeric,
  lvef_cube_duplicate numeric,
  lvedv_mod numeric,
  lvef_geom numeric,
  lvef_teich numeric,
  lvedvi_mod_a4c numeric,
  lvef_teich_duplicate numeric,
  lvedv_mod_a4c numeric,
  lvesv_mod_a4c numeric,
  lvesvi_teich numeric,
  lvedv_cube_duplicate numeric,
  lvef_auto_ef_a4c numeric,
  lvedv_geom numeric,
  lvef_mod_a4c numeric,
  lvedv_mod_a2c numeric,
  lvesvi_teich_duplicate numeric,
  lvesv_auto_ef_a2c numeric,
  lvd_mass_4d_auto_lvq numeric,
  lvs_mass_index_2d numeric,
  lvd_mass_ase numeric,
  lvd_mass numeric,
  lvs_mass_ase numeric,
  lvd_mass_index_ase numeric,
  lvs_mass_ase_duplicate numeric,
  lvd_mass_duplicate numeric,
  lvs_mass numeric,
  lvd_mass_index numeric,
  lvs_mass_a_l numeric,
  lvs_mass_index_mm numeric,
  lvs_mass_duplicate numeric,
  lvco_a_l numeric,
  lvsvi_teich numeric,
  lvsvi_mod_bip numeric,
  lvco_teich numeric,
  lvsv_mod_bip numeric,
  lvsv_teich numeric,
  lvsv_cube_duplicate numeric,
  lvsv_geom numeric,
  lvsv_teich_duplicate numeric,
  lvsvi_mod_a2c numeric,
  lvco_4d_auto_lvq numeric,
  lvsv_auto_ef_a4c numeric,
  lvsvi_teich_duplicate numeric,
  lvsv_4d_auto_lvq numeric,
  lvco_geom numeric,
  lvsv_auto_ef_a2c numeric,
  lvsvi_mod_a4c numeric,
  lvsv_mod_a4c numeric,
  lvsv_mod_a2c numeric,
  lvsvi_cube_duplicate numeric,
  lvci_teich numeric,
  effusion_thickness numeric,
  q_to_pv_closes numeric,
  pv_acc_t_over_et numeric,
  pv_acc_slope numeric,
  pr_max_pg numeric,
  pr_flow numeric,
  pr_vmax numeric,
  pv_max_pg numeric,
  pv_acc_time numeric,
  pr_vti numeric,
  pr_as_sheet text,
  pvet numeric,
  pv_mean_pg numeric,
  pr_pht numeric,
  pv_ann_diam numeric,
  pv_vmean numeric,
  pv_hr numeric,
  pr_dec_time numeric,
  q_to_pv_close_duplicate numeric,
  pr_dec_slope numeric,
  pva_vti numeric,
  pr_vmax_duplicate numeric,
  pr_rad numeric,
  pv_vti numeric,
  pv_vmax numeric,
  pva_vmax numeric,
  ra_short numeric,
  rap numeric,
  ra_lang text,
  raa_s numeric,
  rvidd numeric,
  rvad_a4c numeric,
  ripple text,
  rvas_a4c numeric,
  rvsp numeric,
  rvidd_duplicate numeric,
  rvids numeric,
  rvawd numeric,
  rvids_duplicate numeric,
  rvawd_duplicate numeric,
  rv_hr numeric,
  rvaws_duplicate numeric,
  rvot_diam numeric,
  rvot_vmax numeric,
  rvot_diam_duplicate numeric,
  rvot_diam_index numeric,
  rvot_mean_pg numeric,
  rvot_vmean numeric,
  rvot_max_pg numeric,
  rvot_vti numeric,
  qp_over_qs numeric,
  tv_e_over_a numeric,
  tv_e_deriv numeric,
  tr_ero numeric,
  q_to_tv_itself_opens numeric,
  tv_mean_pg numeric,
  tv_ann_diam numeric,
  tr_mean_pg numeric,
  tva_vti numeric,
  tv_hr numeric,
  tr_vti numeric,
  tr_flow numeric,
  tv_e_about_e_deriv numeric,
  tr_rv numeric,
  tapered text,
  tv_max_pg numeric,
  tv_dec_time numeric,
  tr_vmean numeric,
  tv_vmax numeric,
  tr_rad numeric,
  tva_vmax numeric,
  tv_vti numeric,
  tr_aliasing_velocity numeric,
  tco numeric,
  tv_s_deriv numeric,
  tr_max_pg numeric,
  tr_vmax numeric,
  tr_vmax_duplicate numeric,
  tv_e_velocity numeric,
  tv_vmean numeric,
  q_to_tv_itself_opens_duplicate numeric,
  tv_a_velocity numeric,
  tv_dec_slope numeric,
  ivc_2d numeric,
  source text,
  dcm_refreshed_date_time timestamptz,
  issue_dt timestamptz,
  examination_type text,
  examination_status text,
  accession_number text,
  end_time_of_examination time,
  indication text,
  other text,
  summary text,
  dilation text,
  insufficiency text,
  stenosis text,
  structure text,
  arteria_pulmonalis text,
  mpa text,
  la_size text,
  spontaneous_echocontrast text,
  thrombus text,
  flow text,
  stenosis_set3 text,
  structure_set3 text,
  insufficiency_set3 text,
  ecg text,
  lv_size text,
  fs_perc numeric,
  lv_size_details text,
  vsd text,
  mid_anterolateral text,
  hypertrophy text,
  fract_oppervl_ver text,
  basal_anterolateral text,
  mid_anterior text,
  fract_oppervl_details text,
  basal_anterior text,
  diastolic_filling text,
  basal_inferior text,
  apical_anterior text,
  obstruction_lvot text,
  hypertrophic_cardiomyopathy text,
  wall_motion text,
  ejection_fraction text,
  effusion numeric,
  pericard text,
  insufficiency_set6 text,
  stenosis_set6 text,
  structure_set6 text,
  ra_size text,
  systolic_function text,
  rv_size text,
  insufficiency_duplicate text,
  stenosis_duplicate text,
  structure_duplicate text,
  resp_change text,
  ivc text,
  vcs text,
  flow_patterns_duplicate text,
  lvef_out_summary text
);

INSERT INTO amc_core.echo_measurement_heart_center_extra_check (
  pseudo_id,
  examination_date,
  hospital_location,
  bmi,
  bsa,
  ao_desc_max_pg,
  diam_sinus_valsalva,
  ao_root_diam,
  ao_desc_abd_diam,
  isthmus_ao_diam,
  ao_desc_vmax,
  ao_asc_vmax,
  ao_bow_diam,
  ao_asc_max_pg,
  ao_asc_diam,
  ao_root_diam_duplicate,
  dist_diam_ao_bow,
  ao_st_junct_diam,
  ao_desc_thorac_diam,
  av_slip,
  ar_dec_slope,
  av_ci,
  av_diam,
  av_hr,
  av_max_pg,
  av_co,
  avet,
  ava_planimetry,
  av_vti,
  ar_as_skin,
  ar_vena_contracta,
  ar_rad,
  av_vmax,
  ar_vti,
  ar_flow,
  ar_max_pg,
  av_vmean,
  av_slip_duplicate,
  ar_vmax,
  av_surface,
  ava_vmax,
  ar_vmean,
  ar_rv,
  ar_ero,
  av_mean_pg,
  av_sv,
  ava_vti_index,
  ar_dec_time,
  avai_planimetry,
  ar_rf,
  ar_pht,
  ava_vti,
  ar_mean_pg,
  ar_vmax_duplicate,
  av_si,
  av_diam_index,
  av_diam_duplicate,
  lpa_vmax,
  lpa_max_pg,
  rpa_vmax,
  rpa,
  rpa_max_pg,
  mpa_vmax,
  lpa,
  laesv_a_l_a2c,
  la_short,
  laedv_mod_bip,
  la_lang,
  la_diam,
  la_area,
  laesv_mod_a4c,
  lald_a4c,
  laedv_a_l_a4c,
  laesvi_mod_bip,
  laesv_mod_bip,
  la_over_ao,
  laesvi_a_l,
  la_diam_duplicate,
  laesv_a_l_a4c,
  laa_d2,
  laedvi_a_l,
  laedv_mod_a2c,
  lals_a4c,
  laesv_a_l_bip,
  laesv_mod_a2c,
  laedv_mod_a4c,
  laedv_a_l_bip,
  laad_a4c,
  laas_a4c,
  laa_d1,
  laedv_a_l_a2c,
  p_vein_s_vmax,
  p_vein_a_duration,
  p_vein_a_vmax,
  p_vein_s_over_d,
  p_vein_d_vmax,
  l_ader_a_duration_about_mv_a_duration,
  mr_vmax,
  e_f_slope,
  mv_a_velocity,
  mr_vena_contracta,
  mv_e_over_a,
  mv_e_deriv,
  mv_e_deriv_sept,
  mv_e_deriv_lat,
  mv_e_over_e_deriv_avg,
  mv_a_duration,
  mv_a_deriv_lat,
  mr_vmax_duplicate,
  mr_vmean,
  mv_e_deriv_over_a_deriv_lat,
  mv_e_over_e_deriv_lat,
  mv_co,
  mr_dp_over_dt,
  mva_pht,
  epss,
  mv_pht,
  mv_max_pg,
  mr_rad,
  mv_sv,
  mv_ivrt,
  mr_as_vel,
  mv_acc_time,
  mr_mean_pg,
  mco,
  mv_s_deriv_lat,
  mv_vmax,
  mv_ann_diam,
  mr_max_pg,
  mva_vti,
  mr_ero,
  mr_flow,
  mv_mean_pg,
  mv_s_deriv_sept,
  mv_vmean,
  mv_e_over_e_deriv,
  mr_vti,
  mv_ivct,
  mv_e_deriv_avg,
  mr_vti_duplicate,
  mv_e_over_e_deriv_sept,
  mv_hr,
  mr_rv,
  mr_rf,
  mv_e_velocity,
  mv_e_deriv_over_a_deriv_sept,
  mva_planimetry,
  mv_vti,
  mv_dec_time,
  mv_a_deriv_sept,
  mv_dec_slope,
  bd_syst,
  bd_diast,
  heart_rate,
  lvpw_perc,
  glps_afi_a2c,
  lvids_index,
  mal_pieksys_sl_a4c,
  ivss,
  lvidd_index,
  aa_pieksys_sl_a2c,
  al_pieksys_sl_a4c,
  lvdd_major_a4c,
  lvad_a4c,
  mas_pieksys_sl_aplax,
  mis_pieksys_sl_a4c,
  lvpwd,
  lvad_paras_pm,
  ivsd,
  lvad,
  lvids_index_duplicate,
  glps_afi_a4c,
  limp,
  lvas_a4c,
  glps_4d_auto_lvq,
  ma_pieksys_sl_a2c,
  lvids,
  ba_pieksys_sl_a2c,
  bi_pieksys_sl_a2c,
  mi_pieksys_sl_a2c,
  ap_pieksys_sl_aplax,
  lvas,
  lvas_paras_pm,
  lvas_epi_paras_pm,
  aas_pieksys_sl_aplax,
  lvidd_index_duplicate,
  vsd_size_2,
  bil_pieksys_sl_aplax,
  lv_hr,
  lvidd,
  lvidd_duplicate,
  lvds_major_a4c,
  lvids_duplicate,
  mil_pieksys_sl_aplax,
  lv_hr_duplicate,
  lvld_apical,
  ivss_duplicate,
  lvpws,
  lvrwt,
  lvpwd_duplicate,
  lvdd_major_a2c,
  bas_pieksys_sl_aplax,
  glps_afi_lax,
  bis_pieksys_sl_a4c,
  iv_sd_duplicate,
  lv_hr_bpm_2,
  vsd_size_1,
  lvad_epi_paras_pm,
  lvds_major_a2c,
  as_pieksys_sl_a4c,
  glps_avg_afi,
  lvpw_perc_duplicate,
  lv_fs,
  ball_pieksys_sl_a4c,
  ivs_perc_2d,
  ai_pieksys_sl_a2c,
  lv_fs_duplicate,
  lvpws_duplicate,
  lvls_apical,
  lvot_co,
  lvot_diam,
  dimensionless_index,
  lvot_vmean,
  lvot_sv,
  lvot_vmax,
  lvot_mean_pg,
  lvot_ci,
  lvot_vti,
  lvot_svi,
  lvot_surface,
  lvot_max_pg,
  lvef_auto_ef_a2c,
  lvesv_4d_auto_lvq,
  lvesv_auto_ef_a4c,
  lvef_mod_bip,
  lvedv_4d_auto_lvq,
  lvesv_mod,
  lvedv_teich,
  lvesv_cube,
  lvedv_auto_ef_a2c,
  lvef_mod,
  lvedv_auto_ef_a4c,
  lvedvi_mod_a2c,
  lvef_a_l,
  lvesv_mod_a2c,
  lvef_mod_a2c,
  lvesv_a_l,
  lvedv_teich_duplicate,
  lvesv_geom,
  lvesv_mod_bip,
  lvedvi_mod_bip,
  lvesv_teich,
  lvedvi_teich,
  lvef_4d_auto_lvq,
  lvedv_a_l,
  lvesvi_mod_a2c,
  lvesv_teich_duplicate,
  lvedv_cube,
  lvedvi_teich_duplicate,
  lvef_auto_ef_bip,
  lvedv_mod_bip,
  lvesvi_mod_bip,
  lvesvi_mod_a4c,
  lvef_cube,
  lvesv_cube_duplicate,
  lvef_cube_duplicate,
  lvedv_mod,
  lvef_geom,
  lvef_teich,
  lvedvi_mod_a4c,
  lvef_teich_duplicate,
  lvedv_mod_a4c,
  lvesv_mod_a4c,
  lvesvi_teich,
  lvedv_cube_duplicate,
  lvef_auto_ef_a4c,
  lvedv_geom,
  lvef_mod_a4c,
  lvedv_mod_a2c,
  lvesvi_teich_duplicate,
  lvesv_auto_ef_a2c,
  lvd_mass_4d_auto_lvq,
  lvs_mass_index_2d,
  lvd_mass_ase,
  lvd_mass,
  lvs_mass_ase,
  lvd_mass_index_ase,
  lvs_mass_ase_duplicate,
  lvd_mass_duplicate,
  lvs_mass,
  lvd_mass_index,
  lvs_mass_a_l,
  lvs_mass_index_mm,
  lvs_mass_duplicate,
  lvco_a_l,
  lvsvi_teich,
  lvsvi_mod_bip,
  lvco_teich,
  lvsv_mod_bip,
  lvsv_teich,
  lvsv_cube_duplicate,
  lvsv_geom,
  lvsv_teich_duplicate,
  lvsvi_mod_a2c,
  lvco_4d_auto_lvq,
  lvsv_auto_ef_a4c,
  lvsvi_teich_duplicate,
  lvsv_4d_auto_lvq,
  lvco_geom,
  lvsv_auto_ef_a2c,
  lvsvi_mod_a4c,
  lvsv_mod_a4c,
  lvsv_mod_a2c,
  lvsvi_cube_duplicate,
  lvci_teich,
  effusion_thickness,
  q_to_pv_closes,
  pv_acc_t_over_et,
  pv_acc_slope,
  pr_max_pg,
  pr_flow,
  pr_vmax,
  pv_max_pg,
  pv_acc_time,
  pr_vti,
  pr_as_sheet,
  pvet,
  pv_mean_pg,
  pr_pht,
  pv_ann_diam,
  pv_vmean,
  pv_hr,
  pr_dec_time,
  q_to_pv_close_duplicate,
  pr_dec_slope,
  pva_vti,
  pr_vmax_duplicate,
  pr_rad,
  pv_vti,
  pv_vmax,
  pva_vmax,
  ra_short,
  rap,
  ra_lang,
  raa_s,
  rvidd,
  rvad_a4c,
  ripple,
  rvas_a4c,
  rvsp,
  rvidd_duplicate,
  rvids,
  rvawd,
  rvids_duplicate,
  rvawd_duplicate,
  rv_hr,
  rvaws_duplicate,
  rvot_diam,
  rvot_vmax,
  rvot_diam_duplicate,
  rvot_diam_index,
  rvot_mean_pg,
  rvot_vmean,
  rvot_max_pg,
  rvot_vti,
  qp_over_qs,
  tv_e_over_a,
  tv_e_deriv,
  tr_ero,
  q_to_tv_itself_opens,
  tv_mean_pg,
  tv_ann_diam,
  tr_mean_pg,
  tva_vti,
  tv_hr,
  tr_vti,
  tr_flow,
  tv_e_about_e_deriv,
  tr_rv,
  tapered,
  tv_max_pg,
  tv_dec_time,
  tr_vmean,
  tv_vmax,
  tr_rad,
  tva_vmax,
  tv_vti,
  tr_aliasing_velocity,
  tco,
  tv_s_deriv,
  tr_max_pg,
  tr_vmax,
  tr_vmax_duplicate,
  tv_e_velocity,
  tv_vmean,
  q_to_tv_itself_opens_duplicate,
  tv_a_velocity,
  tv_dec_slope,
  ivc_2d,
  source,
  dcm_refreshed_date_time,
  issue_dt,
  examination_type,
  examination_status,
  accession_number,
  end_time_of_examination,
  indication,
  other,
  summary,
  dilation,
  insufficiency,
  stenosis,
  structure,
  arteria_pulmonalis,
  mpa,
  la_size,
  spontaneous_echocontrast,
  thrombus,
  flow,
  stenosis_set3,
  structure_set3,
  insufficiency_set3,
  ecg,
  lv_size,
  fs_perc,
  lv_size_details,
  vsd,
  mid_anterolateral,
  hypertrophy,
  fract_oppervl_ver,
  basal_anterolateral,
  mid_anterior,
  fract_oppervl_details,
  basal_anterior,
  diastolic_filling,
  basal_inferior,
  apical_anterior,
  obstruction_lvot,
  hypertrophic_cardiomyopathy,
  wall_motion,
  ejection_fraction,
  effusion,
  pericard,
  insufficiency_set6,
  stenosis_set6,
  structure_set6,
  ra_size,
  systolic_function,
  rv_size,
  insufficiency_duplicate,
  stenosis_duplicate,
  structure_duplicate,
  resp_change,
  ivc,
  vcs,
  flow_patterns_duplicate,
  lvef_out_summary
)
SELECT
  NULLIF(pseudo_id, ''),
  NULLIF(examination_date, '')::date,
  NULLIF(hospital_location, ''),
  CASE WHEN trim(bmi) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bmi)::numeric END,
  CASE WHEN trim(bsa) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bsa)::numeric END,
  CASE WHEN trim(ao_desc_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_desc_max_pg)::numeric END,
  CASE WHEN trim(diam_sinus_valsalva) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(diam_sinus_valsalva)::numeric END,
  CASE WHEN trim(ao_root_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_root_diam)::numeric END,
  CASE WHEN trim(ao_desc_abd_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_desc_abd_diam)::numeric END,
  CASE WHEN trim(isthmus_ao_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(isthmus_ao_diam)::numeric END,
  CASE WHEN trim(ao_desc_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_desc_vmax)::numeric END,
  CASE WHEN trim(ao_asc_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_asc_vmax)::numeric END,
  CASE WHEN trim(ao_bow_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_bow_diam)::numeric END,
  CASE WHEN trim(ao_asc_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_asc_max_pg)::numeric END,
  CASE WHEN trim(ao_asc_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_asc_diam)::numeric END,
  CASE WHEN trim(ao_root_diam_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_root_diam_duplicate)::numeric END,
  CASE WHEN trim(dist_diam_ao_bow) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(dist_diam_ao_bow)::numeric END,
  CASE WHEN trim(ao_st_junct_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_st_junct_diam)::numeric END,
  CASE WHEN trim(ao_desc_thorac_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ao_desc_thorac_diam)::numeric END,
  CASE WHEN trim(av_slip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_slip)::numeric END,
  CASE WHEN trim(ar_dec_slope) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_dec_slope)::numeric END,
  CASE WHEN trim(av_ci) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_ci)::numeric END,
  CASE WHEN trim(av_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_diam)::numeric END,
  CASE WHEN trim(av_hr) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_hr)::numeric END,
  CASE WHEN trim(av_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_max_pg)::numeric END,
  CASE WHEN trim(av_co) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_co)::numeric END,
  CASE WHEN trim(avet) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(avet)::numeric END,
  CASE WHEN trim(ava_planimetry) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ava_planimetry)::numeric END,
  CASE WHEN trim(av_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_vti)::numeric END,
  NULLIF(ar_as_skin, ''),
  CASE WHEN trim(ar_vena_contracta) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_vena_contracta)::numeric END,
  CASE WHEN trim(ar_rad) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_rad)::numeric END,
  CASE WHEN trim(av_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_vmax)::numeric END,
  CASE WHEN trim(ar_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_vti)::numeric END,
  CASE WHEN trim(ar_flow) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_flow)::numeric END,
  CASE WHEN trim(ar_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_max_pg)::numeric END,
  CASE WHEN trim(av_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_vmean)::numeric END,
  CASE WHEN trim(av_slip_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_slip_duplicate)::numeric END,
  CASE WHEN trim(ar_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_vmax)::numeric END,
  CASE WHEN trim(av_surface) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_surface)::numeric END,
  CASE WHEN trim(ava_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ava_vmax)::numeric END,
  CASE WHEN trim(ar_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_vmean)::numeric END,
  CASE WHEN trim(ar_rv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_rv)::numeric END,
  CASE WHEN trim(ar_ero) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_ero)::numeric END,
  CASE WHEN trim(av_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_mean_pg)::numeric END,
  CASE WHEN trim(av_sv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_sv)::numeric END,
  CASE WHEN trim(ava_vti_index) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ava_vti_index)::numeric END,
  CASE WHEN trim(ar_dec_time) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_dec_time)::numeric END,
  CASE WHEN trim(avai_planimetry) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(avai_planimetry)::numeric END,
  CASE WHEN trim(ar_rf) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_rf)::numeric END,
  CASE WHEN trim(ar_pht) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_pht)::numeric END,
  CASE WHEN trim(ava_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ava_vti)::numeric END,
  CASE WHEN trim(ar_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_mean_pg)::numeric END,
  CASE WHEN trim(ar_vmax_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ar_vmax_duplicate)::numeric END,
  CASE WHEN trim(av_si) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_si)::numeric END,
  CASE WHEN trim(av_diam_index) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_diam_index)::numeric END,
  CASE WHEN trim(av_diam_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(av_diam_duplicate)::numeric END,
  CASE WHEN trim(lpa_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lpa_vmax)::numeric END,
  CASE WHEN trim(lpa_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lpa_max_pg)::numeric END,
  CASE WHEN trim(rpa_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rpa_vmax)::numeric END,
  NULLIF(rpa, ''),
  CASE WHEN trim(rpa_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rpa_max_pg)::numeric END,
  CASE WHEN trim(mpa_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mpa_vmax)::numeric END,
  NULLIF(lpa, ''),
  CASE WHEN trim(laesv_a_l_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesv_a_l_a2c)::numeric END,
  CASE WHEN trim(la_short) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(la_short)::numeric END,
  CASE WHEN trim(laedv_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laedv_mod_bip)::numeric END,
  NULLIF(la_lang, ''),
  CASE WHEN trim(la_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(la_diam)::numeric END,
  CASE WHEN trim(la_area) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(la_area)::numeric END,
  CASE WHEN trim(laesv_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesv_mod_a4c)::numeric END,
  CASE WHEN trim(lald_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lald_a4c)::numeric END,
  CASE WHEN trim(laedv_a_l_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laedv_a_l_a4c)::numeric END,
  CASE WHEN trim(laesvi_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesvi_mod_bip)::numeric END,
  CASE WHEN trim(laesv_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesv_mod_bip)::numeric END,
  CASE WHEN trim(la_over_ao) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(la_over_ao)::numeric END,
  CASE WHEN trim(laesvi_a_l) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesvi_a_l)::numeric END,
  CASE WHEN trim(la_diam_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(la_diam_duplicate)::numeric END,
  CASE WHEN trim(laesv_a_l_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesv_a_l_a4c)::numeric END,
  CASE WHEN trim(laa_d2) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laa_d2)::numeric END,
  CASE WHEN trim(laedvi_a_l) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laedvi_a_l)::numeric END,
  CASE WHEN trim(laedv_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laedv_mod_a2c)::numeric END,
  CASE WHEN trim(lals_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lals_a4c)::numeric END,
  CASE WHEN trim(laesv_a_l_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesv_a_l_bip)::numeric END,
  CASE WHEN trim(laesv_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laesv_mod_a2c)::numeric END,
  CASE WHEN trim(laedv_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laedv_mod_a4c)::numeric END,
  CASE WHEN trim(laedv_a_l_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laedv_a_l_bip)::numeric END,
  CASE WHEN trim(laad_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laad_a4c)::numeric END,
  CASE WHEN trim(laas_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laas_a4c)::numeric END,
  CASE WHEN trim(laa_d1) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laa_d1)::numeric END,
  CASE WHEN trim(laedv_a_l_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(laedv_a_l_a2c)::numeric END,
  CASE WHEN trim(p_vein_s_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(p_vein_s_vmax)::numeric END,
  CASE WHEN trim(p_vein_a_duration) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(p_vein_a_duration)::numeric END,
  CASE WHEN trim(p_vein_a_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(p_vein_a_vmax)::numeric END,
  CASE WHEN trim(p_vein_s_over_d) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(p_vein_s_over_d)::numeric END,
  CASE WHEN trim(p_vein_d_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(p_vein_d_vmax)::numeric END,
  CASE WHEN trim(l_ader_a_duration_about_mv_a_duration) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(l_ader_a_duration_about_mv_a_duration)::numeric END,
  CASE WHEN trim(mr_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_vmax)::numeric END,
  CASE WHEN trim(e_f_slope) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(e_f_slope)::numeric END,
  CASE WHEN trim(mv_a_velocity) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_a_velocity)::numeric END,
  CASE WHEN trim(mr_vena_contracta) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_vena_contracta)::numeric END,
  CASE WHEN trim(mv_e_over_a) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_over_a)::numeric END,
  CASE WHEN trim(mv_e_deriv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_deriv)::numeric END,
  CASE WHEN trim(mv_e_deriv_sept) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_deriv_sept)::numeric END,
  CASE WHEN trim(mv_e_deriv_lat) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_deriv_lat)::numeric END,
  CASE WHEN trim(mv_e_over_e_deriv_avg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_over_e_deriv_avg)::numeric END,
  CASE WHEN trim(mv_a_duration) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_a_duration)::numeric END,
  CASE WHEN trim(mv_a_deriv_lat) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_a_deriv_lat)::numeric END,
  CASE WHEN trim(mr_vmax_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_vmax_duplicate)::numeric END,
  CASE WHEN trim(mr_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_vmean)::numeric END,
  CASE WHEN trim(mv_e_deriv_over_a_deriv_lat) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_deriv_over_a_deriv_lat)::numeric END,
  CASE WHEN trim(mv_e_over_e_deriv_lat) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_over_e_deriv_lat)::numeric END,
  CASE WHEN trim(mv_co) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_co)::numeric END,
  CASE WHEN trim(mr_dp_over_dt) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_dp_over_dt)::numeric END,
  CASE WHEN trim(mva_pht) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mva_pht)::numeric END,
  CASE WHEN trim(epss) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(epss)::numeric END,
  CASE WHEN trim(mv_pht) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_pht)::numeric END,
  CASE WHEN trim(mv_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_max_pg)::numeric END,
  CASE WHEN trim(mr_rad) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_rad)::numeric END,
  CASE WHEN trim(mv_sv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_sv)::numeric END,
  CASE WHEN trim(mv_ivrt) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_ivrt)::numeric END,
  CASE WHEN trim(mr_as_vel) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_as_vel)::numeric END,
  CASE WHEN trim(mv_acc_time) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_acc_time)::numeric END,
  CASE WHEN trim(mr_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_mean_pg)::numeric END,
  CASE WHEN trim(mco) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mco)::numeric END,
  CASE WHEN trim(mv_s_deriv_lat) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_s_deriv_lat)::numeric END,
  CASE WHEN trim(mv_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_vmax)::numeric END,
  CASE WHEN trim(mv_ann_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_ann_diam)::numeric END,
  CASE WHEN trim(mr_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_max_pg)::numeric END,
  CASE WHEN trim(mva_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mva_vti)::numeric END,
  CASE WHEN trim(mr_ero) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_ero)::numeric END,
  CASE WHEN trim(mr_flow) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_flow)::numeric END,
  CASE WHEN trim(mv_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_mean_pg)::numeric END,
  CASE WHEN trim(mv_s_deriv_sept) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_s_deriv_sept)::numeric END,
  CASE WHEN trim(mv_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_vmean)::numeric END,
  CASE WHEN trim(mv_e_over_e_deriv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_over_e_deriv)::numeric END,
  CASE WHEN trim(mr_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_vti)::numeric END,
  CASE WHEN trim(mv_ivct) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_ivct)::numeric END,
  CASE WHEN trim(mv_e_deriv_avg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_deriv_avg)::numeric END,
  CASE WHEN trim(mr_vti_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_vti_duplicate)::numeric END,
  CASE WHEN trim(mv_e_over_e_deriv_sept) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_over_e_deriv_sept)::numeric END,
  CASE WHEN trim(mv_hr) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_hr)::numeric END,
  CASE WHEN trim(mr_rv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_rv)::numeric END,
  CASE WHEN trim(mr_rf) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mr_rf)::numeric END,
  CASE WHEN trim(mv_e_velocity) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_velocity)::numeric END,
  CASE WHEN trim(mv_e_deriv_over_a_deriv_sept) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_e_deriv_over_a_deriv_sept)::numeric END,
  CASE WHEN trim(mva_planimetry) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mva_planimetry)::numeric END,
  CASE WHEN trim(mv_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_vti)::numeric END,
  CASE WHEN trim(mv_dec_time) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_dec_time)::numeric END,
  CASE WHEN trim(mv_a_deriv_sept) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_a_deriv_sept)::numeric END,
  CASE WHEN trim(mv_dec_slope) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mv_dec_slope)::numeric END,
  CASE WHEN trim(bd_syst) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bd_syst)::numeric END,
  CASE WHEN trim(bd_diast) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bd_diast)::numeric END,
  CASE WHEN trim(heart_rate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(heart_rate)::numeric END,
  CASE WHEN trim(lvpw_perc) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvpw_perc)::numeric END,
  CASE WHEN trim(glps_afi_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(glps_afi_a2c)::numeric END,
  CASE WHEN trim(lvids_index) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvids_index)::numeric END,
  CASE WHEN trim(mal_pieksys_sl_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mal_pieksys_sl_a4c)::numeric END,
  CASE WHEN trim(ivss) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ivss)::numeric END,
  CASE WHEN trim(lvidd_index) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvidd_index)::numeric END,
  CASE WHEN trim(aa_pieksys_sl_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(aa_pieksys_sl_a2c)::numeric END,
  CASE WHEN trim(al_pieksys_sl_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(al_pieksys_sl_a4c)::numeric END,
  CASE WHEN trim(lvdd_major_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvdd_major_a4c)::numeric END,
  CASE WHEN trim(lvad_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvad_a4c)::numeric END,
  CASE WHEN trim(mas_pieksys_sl_aplax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mas_pieksys_sl_aplax)::numeric END,
  CASE WHEN trim(mis_pieksys_sl_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mis_pieksys_sl_a4c)::numeric END,
  CASE WHEN trim(lvpwd) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvpwd)::numeric END,
  CASE WHEN trim(lvad_paras_pm) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvad_paras_pm)::numeric END,
  CASE WHEN trim(ivsd) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ivsd)::numeric END,
  CASE WHEN trim(lvad) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvad)::numeric END,
  CASE WHEN trim(lvids_index_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvids_index_duplicate)::numeric END,
  CASE WHEN trim(glps_afi_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(glps_afi_a4c)::numeric END,
  NULLIF(limp, ''),
  CASE WHEN trim(lvas_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvas_a4c)::numeric END,
  NULLIF(glps_4d_auto_lvq, ''),
  CASE WHEN trim(ma_pieksys_sl_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ma_pieksys_sl_a2c)::numeric END,
  CASE WHEN trim(lvids) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvids)::numeric END,
  CASE WHEN trim(ba_pieksys_sl_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ba_pieksys_sl_a2c)::numeric END,
  CASE WHEN trim(bi_pieksys_sl_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bi_pieksys_sl_a2c)::numeric END,
  CASE WHEN trim(mi_pieksys_sl_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mi_pieksys_sl_a2c)::numeric END,
  CASE WHEN trim(ap_pieksys_sl_aplax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ap_pieksys_sl_aplax)::numeric END,
  CASE WHEN trim(lvas) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvas)::numeric END,
  CASE WHEN trim(lvas_paras_pm) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvas_paras_pm)::numeric END,
  CASE WHEN trim(lvas_epi_paras_pm) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvas_epi_paras_pm)::numeric END,
  CASE WHEN trim(aas_pieksys_sl_aplax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(aas_pieksys_sl_aplax)::numeric END,
  CASE WHEN trim(lvidd_index_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvidd_index_duplicate)::numeric END,
  CASE WHEN trim(vsd_size_2) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(vsd_size_2)::numeric END,
  CASE WHEN trim(bil_pieksys_sl_aplax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bil_pieksys_sl_aplax)::numeric END,
  CASE WHEN trim(lv_hr) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lv_hr)::numeric END,
  CASE WHEN trim(lvidd) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvidd)::numeric END,
  CASE WHEN trim(lvidd_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvidd_duplicate)::numeric END,
  CASE WHEN trim(lvds_major_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvds_major_a4c)::numeric END,
  CASE WHEN trim(lvids_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvids_duplicate)::numeric END,
  CASE WHEN trim(mil_pieksys_sl_aplax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(mil_pieksys_sl_aplax)::numeric END,
  CASE WHEN trim(lv_hr_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lv_hr_duplicate)::numeric END,
  CASE WHEN trim(lvld_apical) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvld_apical)::numeric END,
  CASE WHEN trim(ivss_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ivss_duplicate)::numeric END,
  CASE WHEN trim(lvpws) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvpws)::numeric END,
  CASE WHEN trim(lvrwt) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvrwt)::numeric END,
  CASE WHEN trim(lvpwd_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvpwd_duplicate)::numeric END,
  CASE WHEN trim(lvdd_major_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvdd_major_a2c)::numeric END,
  CASE WHEN trim(bas_pieksys_sl_aplax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bas_pieksys_sl_aplax)::numeric END,
  CASE WHEN trim(glps_afi_lax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(glps_afi_lax)::numeric END,
  CASE WHEN trim(bis_pieksys_sl_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(bis_pieksys_sl_a4c)::numeric END,
  CASE WHEN trim(iv_sd_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(iv_sd_duplicate)::numeric END,
  CASE WHEN trim(lv_hr_bpm_2) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lv_hr_bpm_2)::numeric END,
  CASE WHEN trim(vsd_size_1) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(vsd_size_1)::numeric END,
  CASE WHEN trim(lvad_epi_paras_pm) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvad_epi_paras_pm)::numeric END,
  CASE WHEN trim(lvds_major_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvds_major_a2c)::numeric END,
  CASE WHEN trim(as_pieksys_sl_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(as_pieksys_sl_a4c)::numeric END,
  NULLIF(glps_avg_afi, ''),
  CASE WHEN trim(lvpw_perc_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvpw_perc_duplicate)::numeric END,
  CASE WHEN trim(lv_fs) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lv_fs)::numeric END,
  CASE WHEN trim(ball_pieksys_sl_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ball_pieksys_sl_a4c)::numeric END,
  CASE WHEN trim(ivs_perc_2d) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ivs_perc_2d)::numeric END,
  CASE WHEN trim(ai_pieksys_sl_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ai_pieksys_sl_a2c)::numeric END,
  CASE WHEN trim(lv_fs_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lv_fs_duplicate)::numeric END,
  CASE WHEN trim(lvpws_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvpws_duplicate)::numeric END,
  CASE WHEN trim(lvls_apical) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvls_apical)::numeric END,
  CASE WHEN trim(lvot_co) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_co)::numeric END,
  CASE WHEN trim(lvot_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_diam)::numeric END,
  CASE WHEN trim(dimensionless_index) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(dimensionless_index)::numeric END,
  CASE WHEN trim(lvot_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_vmean)::numeric END,
  CASE WHEN trim(lvot_sv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_sv)::numeric END,
  CASE WHEN trim(lvot_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_vmax)::numeric END,
  CASE WHEN trim(lvot_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_mean_pg)::numeric END,
  CASE WHEN trim(lvot_ci) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_ci)::numeric END,
  CASE WHEN trim(lvot_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_vti)::numeric END,
  CASE WHEN trim(lvot_svi) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_svi)::numeric END,
  CASE WHEN trim(lvot_surface) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_surface)::numeric END,
  CASE WHEN trim(lvot_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvot_max_pg)::numeric END,
  CASE WHEN trim(lvef_auto_ef_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_auto_ef_a2c)::numeric END,
  CASE WHEN trim(lvesv_4d_auto_lvq) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_4d_auto_lvq)::numeric END,
  CASE WHEN trim(lvesv_auto_ef_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_auto_ef_a4c)::numeric END,
  CASE WHEN trim(lvef_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_mod_bip)::numeric END,
  CASE WHEN trim(lvedv_4d_auto_lvq) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_4d_auto_lvq)::numeric END,
  CASE WHEN trim(lvesv_mod) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_mod)::numeric END,
  CASE WHEN trim(lvedv_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_teich)::numeric END,
  CASE WHEN trim(lvesv_cube) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_cube)::numeric END,
  CASE WHEN trim(lvedv_auto_ef_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_auto_ef_a2c)::numeric END,
  CASE WHEN trim(lvef_mod) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_mod)::numeric END,
  CASE WHEN trim(lvedv_auto_ef_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_auto_ef_a4c)::numeric END,
  CASE WHEN trim(lvedvi_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedvi_mod_a2c)::numeric END,
  CASE WHEN trim(lvef_a_l) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_a_l)::numeric END,
  CASE WHEN trim(lvesv_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_mod_a2c)::numeric END,
  CASE WHEN trim(lvef_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_mod_a2c)::numeric END,
  CASE WHEN trim(lvesv_a_l) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_a_l)::numeric END,
  CASE WHEN trim(lvedv_teich_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_teich_duplicate)::numeric END,
  CASE WHEN trim(lvesv_geom) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_geom)::numeric END,
  CASE WHEN trim(lvesv_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_mod_bip)::numeric END,
  CASE WHEN trim(lvedvi_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedvi_mod_bip)::numeric END,
  CASE WHEN trim(lvesv_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_teich)::numeric END,
  CASE WHEN trim(lvedvi_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedvi_teich)::numeric END,
  CASE WHEN trim(lvef_4d_auto_lvq) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_4d_auto_lvq)::numeric END,
  CASE WHEN trim(lvedv_a_l) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_a_l)::numeric END,
  CASE WHEN trim(lvesvi_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesvi_mod_a2c)::numeric END,
  CASE WHEN trim(lvesv_teich_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_teich_duplicate)::numeric END,
  CASE WHEN trim(lvedv_cube) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_cube)::numeric END,
  CASE WHEN trim(lvedvi_teich_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedvi_teich_duplicate)::numeric END,
  CASE WHEN trim(lvef_auto_ef_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_auto_ef_bip)::numeric END,
  CASE WHEN trim(lvedv_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_mod_bip)::numeric END,
  CASE WHEN trim(lvesvi_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesvi_mod_bip)::numeric END,
  CASE WHEN trim(lvesvi_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesvi_mod_a4c)::numeric END,
  CASE WHEN trim(lvef_cube) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_cube)::numeric END,
  CASE WHEN trim(lvesv_cube_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_cube_duplicate)::numeric END,
  CASE WHEN trim(lvef_cube_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_cube_duplicate)::numeric END,
  CASE WHEN trim(lvedv_mod) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_mod)::numeric END,
  CASE WHEN trim(lvef_geom) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_geom)::numeric END,
  CASE WHEN trim(lvef_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_teich)::numeric END,
  CASE WHEN trim(lvedvi_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedvi_mod_a4c)::numeric END,
  CASE WHEN trim(lvef_teich_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_teich_duplicate)::numeric END,
  CASE WHEN trim(lvedv_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_mod_a4c)::numeric END,
  CASE WHEN trim(lvesv_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_mod_a4c)::numeric END,
  CASE WHEN trim(lvesvi_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesvi_teich)::numeric END,
  CASE WHEN trim(lvedv_cube_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_cube_duplicate)::numeric END,
  CASE WHEN trim(lvef_auto_ef_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_auto_ef_a4c)::numeric END,
  CASE WHEN trim(lvedv_geom) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_geom)::numeric END,
  CASE WHEN trim(lvef_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvef_mod_a4c)::numeric END,
  CASE WHEN trim(lvedv_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvedv_mod_a2c)::numeric END,
  CASE WHEN trim(lvesvi_teich_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesvi_teich_duplicate)::numeric END,
  CASE WHEN trim(lvesv_auto_ef_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvesv_auto_ef_a2c)::numeric END,
  CASE WHEN trim(lvd_mass_4d_auto_lvq) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvd_mass_4d_auto_lvq)::numeric END,
  CASE WHEN trim(lvs_mass_index_2d) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvs_mass_index_2d)::numeric END,
  CASE WHEN trim(lvd_mass_ase) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvd_mass_ase)::numeric END,
  CASE WHEN trim(lvd_mass) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvd_mass)::numeric END,
  CASE WHEN trim(lvs_mass_ase) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvs_mass_ase)::numeric END,
  CASE WHEN trim(lvd_mass_index_ase) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvd_mass_index_ase)::numeric END,
  CASE WHEN trim(lvs_mass_ase_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvs_mass_ase_duplicate)::numeric END,
  CASE WHEN trim(lvd_mass_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvd_mass_duplicate)::numeric END,
  CASE WHEN trim(lvs_mass) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvs_mass)::numeric END,
  CASE WHEN trim(lvd_mass_index) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvd_mass_index)::numeric END,
  CASE WHEN trim(lvs_mass_a_l) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvs_mass_a_l)::numeric END,
  CASE WHEN trim(lvs_mass_index_mm) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvs_mass_index_mm)::numeric END,
  CASE WHEN trim(lvs_mass_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvs_mass_duplicate)::numeric END,
  CASE WHEN trim(lvco_a_l) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvco_a_l)::numeric END,
  CASE WHEN trim(lvsvi_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsvi_teich)::numeric END,
  CASE WHEN trim(lvsvi_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsvi_mod_bip)::numeric END,
  CASE WHEN trim(lvco_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvco_teich)::numeric END,
  CASE WHEN trim(lvsv_mod_bip) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_mod_bip)::numeric END,
  CASE WHEN trim(lvsv_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_teich)::numeric END,
  CASE WHEN trim(lvsv_cube_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_cube_duplicate)::numeric END,
  CASE WHEN trim(lvsv_geom) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_geom)::numeric END,
  CASE WHEN trim(lvsv_teich_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_teich_duplicate)::numeric END,
  CASE WHEN trim(lvsvi_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsvi_mod_a2c)::numeric END,
  CASE WHEN trim(lvco_4d_auto_lvq) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvco_4d_auto_lvq)::numeric END,
  CASE WHEN trim(lvsv_auto_ef_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_auto_ef_a4c)::numeric END,
  CASE WHEN trim(lvsvi_teich_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsvi_teich_duplicate)::numeric END,
  CASE WHEN trim(lvsv_4d_auto_lvq) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_4d_auto_lvq)::numeric END,
  CASE WHEN trim(lvco_geom) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvco_geom)::numeric END,
  CASE WHEN trim(lvsv_auto_ef_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_auto_ef_a2c)::numeric END,
  CASE WHEN trim(lvsvi_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsvi_mod_a4c)::numeric END,
  CASE WHEN trim(lvsv_mod_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_mod_a4c)::numeric END,
  CASE WHEN trim(lvsv_mod_a2c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsv_mod_a2c)::numeric END,
  CASE WHEN trim(lvsvi_cube_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvsvi_cube_duplicate)::numeric END,
  CASE WHEN trim(lvci_teich) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(lvci_teich)::numeric END,
  CASE WHEN trim(effusion_thickness) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(effusion_thickness)::numeric END,
  CASE WHEN trim(q_to_pv_closes) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(q_to_pv_closes)::numeric END,
  CASE WHEN trim(pv_acc_t_over_et) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_acc_t_over_et)::numeric END,
  CASE WHEN trim(pv_acc_slope) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_acc_slope)::numeric END,
  CASE WHEN trim(pr_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_max_pg)::numeric END,
  CASE WHEN trim(pr_flow) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_flow)::numeric END,
  CASE WHEN trim(pr_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_vmax)::numeric END,
  CASE WHEN trim(pv_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_max_pg)::numeric END,
  CASE WHEN trim(pv_acc_time) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_acc_time)::numeric END,
  CASE WHEN trim(pr_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_vti)::numeric END,
  NULLIF(pr_as_sheet, ''),
  CASE WHEN trim(pvet) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pvet)::numeric END,
  CASE WHEN trim(pv_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_mean_pg)::numeric END,
  CASE WHEN trim(pr_pht) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_pht)::numeric END,
  CASE WHEN trim(pv_ann_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_ann_diam)::numeric END,
  CASE WHEN trim(pv_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_vmean)::numeric END,
  CASE WHEN trim(pv_hr) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_hr)::numeric END,
  CASE WHEN trim(pr_dec_time) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_dec_time)::numeric END,
  CASE WHEN trim(q_to_pv_close_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(q_to_pv_close_duplicate)::numeric END,
  CASE WHEN trim(pr_dec_slope) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_dec_slope)::numeric END,
  CASE WHEN trim(pva_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pva_vti)::numeric END,
  CASE WHEN trim(pr_vmax_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_vmax_duplicate)::numeric END,
  CASE WHEN trim(pr_rad) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pr_rad)::numeric END,
  CASE WHEN trim(pv_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_vti)::numeric END,
  CASE WHEN trim(pv_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pv_vmax)::numeric END,
  CASE WHEN trim(pva_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(pva_vmax)::numeric END,
  CASE WHEN trim(ra_short) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ra_short)::numeric END,
  CASE WHEN trim(rap) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rap)::numeric END,
  NULLIF(ra_lang, ''),
  CASE WHEN trim(raa_s) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(raa_s)::numeric END,
  CASE WHEN trim(rvidd) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvidd)::numeric END,
  CASE WHEN trim(rvad_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvad_a4c)::numeric END,
  NULLIF(ripple, ''),
  CASE WHEN trim(rvas_a4c) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvas_a4c)::numeric END,
  CASE WHEN trim(rvsp) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvsp)::numeric END,
  CASE WHEN trim(rvidd_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvidd_duplicate)::numeric END,
  CASE WHEN trim(rvids) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvids)::numeric END,
  CASE WHEN trim(rvawd) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvawd)::numeric END,
  CASE WHEN trim(rvids_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvids_duplicate)::numeric END,
  CASE WHEN trim(rvawd_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvawd_duplicate)::numeric END,
  CASE WHEN trim(rv_hr) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rv_hr)::numeric END,
  CASE WHEN trim(rvaws_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvaws_duplicate)::numeric END,
  CASE WHEN trim(rvot_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_diam)::numeric END,
  CASE WHEN trim(rvot_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_vmax)::numeric END,
  CASE WHEN trim(rvot_diam_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_diam_duplicate)::numeric END,
  CASE WHEN trim(rvot_diam_index) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_diam_index)::numeric END,
  CASE WHEN trim(rvot_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_mean_pg)::numeric END,
  CASE WHEN trim(rvot_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_vmean)::numeric END,
  CASE WHEN trim(rvot_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_max_pg)::numeric END,
  CASE WHEN trim(rvot_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(rvot_vti)::numeric END,
  CASE WHEN trim(qp_over_qs) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(qp_over_qs)::numeric END,
  CASE WHEN trim(tv_e_over_a) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_e_over_a)::numeric END,
  CASE WHEN trim(tv_e_deriv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_e_deriv)::numeric END,
  CASE WHEN trim(tr_ero) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_ero)::numeric END,
  CASE WHEN trim(q_to_tv_itself_opens) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(q_to_tv_itself_opens)::numeric END,
  CASE WHEN trim(tv_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_mean_pg)::numeric END,
  CASE WHEN trim(tv_ann_diam) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_ann_diam)::numeric END,
  CASE WHEN trim(tr_mean_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_mean_pg)::numeric END,
  CASE WHEN trim(tva_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tva_vti)::numeric END,
  CASE WHEN trim(tv_hr) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_hr)::numeric END,
  CASE WHEN trim(tr_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_vti)::numeric END,
  CASE WHEN trim(tr_flow) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_flow)::numeric END,
  CASE WHEN trim(tv_e_about_e_deriv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_e_about_e_deriv)::numeric END,
  CASE WHEN trim(tr_rv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_rv)::numeric END,
  NULLIF(tapered, ''),
  CASE WHEN trim(tv_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_max_pg)::numeric END,
  CASE WHEN trim(tv_dec_time) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_dec_time)::numeric END,
  CASE WHEN trim(tr_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_vmean)::numeric END,
  CASE WHEN trim(tv_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_vmax)::numeric END,
  CASE WHEN trim(tr_rad) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_rad)::numeric END,
  CASE WHEN trim(tva_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tva_vmax)::numeric END,
  CASE WHEN trim(tv_vti) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_vti)::numeric END,
  CASE WHEN trim(tr_aliasing_velocity) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_aliasing_velocity)::numeric END,
  CASE WHEN trim(tco) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tco)::numeric END,
  CASE WHEN trim(tv_s_deriv) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_s_deriv)::numeric END,
  CASE WHEN trim(tr_max_pg) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_max_pg)::numeric END,
  CASE WHEN trim(tr_vmax) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_vmax)::numeric END,
  CASE WHEN trim(tr_vmax_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tr_vmax_duplicate)::numeric END,
  CASE WHEN trim(tv_e_velocity) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_e_velocity)::numeric END,
  CASE WHEN trim(tv_vmean) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_vmean)::numeric END,
  CASE WHEN trim(q_to_tv_itself_opens_duplicate) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(q_to_tv_itself_opens_duplicate)::numeric END,
  CASE WHEN trim(tv_a_velocity) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_a_velocity)::numeric END,
  CASE WHEN trim(tv_dec_slope) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(tv_dec_slope)::numeric END,
  CASE WHEN trim(ivc_2d) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(ivc_2d)::numeric END,
  NULLIF(source, ''),
  NULLIF(dcm_refreshed_date_time, '')::timestamptz,
  NULLIF(issue_dt, '')::timestamptz,
  NULLIF(examination_type, ''),
  NULLIF(examination_status, ''),
  NULLIF(accession_number, ''),
  NULLIF(end_time_of_examination, '')::time,
  NULLIF(indication, ''),
  NULLIF(other, ''),
  NULLIF(summary, ''),
  NULLIF(dilation, ''),
  NULLIF(insufficiency, ''),
  NULLIF(stenosis, ''),
  NULLIF(structure, ''),
  NULLIF(arteria_pulmonalis, ''),
  NULLIF(mpa, ''),
  NULLIF(la_size, ''),
  NULLIF(spontaneous_echocontrast, ''),
  NULLIF(thrombus, ''),
  NULLIF(flow, ''),
  NULLIF(stenosis_set3, ''),
  NULLIF(structure_set3, ''),
  NULLIF(insufficiency_set3, ''),
  NULLIF(ecg, ''),
  NULLIF(lv_size, ''),
  CASE WHEN trim(fs_perc) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(fs_perc)::numeric END,
  NULLIF(lv_size_details, ''),
  NULLIF(vsd, ''),
  NULLIF(mid_anterolateral, ''),
  NULLIF(hypertrophy, ''),
  NULLIF(fract_oppervl_ver, ''),
  NULLIF(basal_anterolateral, ''),
  NULLIF(mid_anterior, ''),
  NULLIF(fract_oppervl_details, ''),
  NULLIF(basal_anterior, ''),
  NULLIF(diastolic_filling, ''),
  NULLIF(basal_inferior, ''),
  NULLIF(apical_anterior, ''),
  NULLIF(obstruction_lvot, ''),
  NULLIF(hypertrophic_cardiomyopathy, ''),
  NULLIF(wall_motion, ''),
  NULLIF(ejection_fraction, ''),
  CASE WHEN trim(effusion) ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN trim(effusion)::numeric END,
  NULLIF(pericard, ''),
  NULLIF(insufficiency_set6, ''),
  NULLIF(stenosis_set6, ''),
  NULLIF(structure_set6, ''),
  NULLIF(ra_size, ''),
  NULLIF(systolic_function, ''),
  NULLIF(rv_size, ''),
  NULLIF(insufficiency_duplicate, ''),
  NULLIF(stenosis_duplicate, ''),
  NULLIF(structure_duplicate, ''),
  NULLIF(resp_change, ''),
  NULLIF(ivc, ''),
  NULLIF(vcs, ''),
  NULLIF(flow_patterns_duplicate, ''),
  NULLIF(lvef_out_summary, '')
FROM amc_raw.echo_measurement_heart_center_extra_check;

CREATE INDEX IF NOT EXISTS idx_core_echo_heart_extra_pseudo_id
  ON amc_core.echo_measurement_heart_center_extra_check(pseudo_id);
