--============================================================
-- New table, first appears in the 2026-09-08 extract.
DROP TABLE IF EXISTS amc_raw.emergency_care_traject;

CREATE TABLE amc_raw.emergency_care_traject (
  pseudo_id TEXT,
  emergency_care_traject_id TEXT,
  patient_contact_id TEXT,
  hospital_location TEXT,
  emergency_care_event_created_moment TEXT,
  emergency_care_event_created_date TEXT,
  emergency_care_event_created_time TEXT,
  emergency_care_event_patient_arrived_moment TEXT,
  emergency_care_event_patient_arrived_date TEXT,
  emergency_care_event_patient_arrived_time TEXT,
  emergency_care_admission_start_moment TEXT,
  emergency_care_admission_start_date TEXT,
  emergency_care_admission_start_time TEXT,
  emergency_care_admission_end_moment TEXT,
  emergency_care_admission_end_date TEXT,
  emergency_care_admission_end_time TEXT,
  emergency_care_event_arrival_workplace TEXT,
  emergency_care_arrival_mode TEXT,
  emergency_care_admission_subspecialty TEXT,
  emergency_care_triage TEXT,
  chief_emergency_care_complaint TEXT,
  chief_emergency_care_input_complaint TEXT,
  emergency_care_admission_arrival_subspecialty TEXT,
  emergency_care_admission_departure_subspecialty TEXT,
  emergency_care_admission_arrival_workplace TEXT,
  emergency_care_admission_next_workplace TEXT,
  emergency_care_admission_departure_to_workplace TEXT,
  destination_after_emergency_care TEXT,
  emergency_care_duration_class TEXT,
  emergency_care_presentation_type TEXT,
  is_clinical_follow_up TEXT,
  is_high_care TEXT,
  is_ehh_traject TEXT,
  is_patient_discharged TEXT,
  is_emergency_care_event_created TEXT,
  is_emergency_care_event_arrived TEXT,
  is_emergency_care_event_end TEXT,
  emergency_care_admission_duration_minutes TEXT,
  emergency_care_admission_duration_hours TEXT,
  emergency_care_stay_duration_minutes TEXT,
  emergency_care_waiting_time_minutes TEXT,
  number_emergency_care_trajects TEXT,
  number_emergency_care_admission_partial_trajects TEXT,
  number_emergency_care_stays_shorter_than_4_hours TEXT,
  number_emergency_care_stays_longer_than_4_hours TEXT,
  issue_dt TEXT
);

-- @COPY_PARTS: emergency_care_traject
